services:
  - type: web
    name: backend-repo
    env: python
    plan: standard
    buildCommand: 
      - apt-get update && apt-get install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
      - pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
