services:
  - type: web
    name: fastapi-backend
    env: python
    plan: free
    buildCommand: "poetry install"
    startCommand: "poetry run uvicorn main:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    healthCheckPath: "/health"
